FROM python:3.8

# set a directory for the app
WORKDIR C:\Users\Owner\Documents\UChicago\Fall_2022\Topics_in_SWE\404_team_not_found-prajval\404_team_not_found\front

# copy all the files to the container
COPY . .

# install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# define the port number the container should expose
EXPOSE 5000

# run the command
CMD ["python", "./app.py"]