FROM python:3.8

# set a directory for the app
WORKDIR "E:\Quarter 4\Topics in Software Engineering\Code\Item_Service"

# copy all the files to the container
COPY . .

# install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# define the port number the container should expose
EXPOSE 5000

# run the command
CMD ["python", "./app.py"]