# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: items.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bitems.proto\x12\x05items\"\x86\x01\n\x04Item\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x11\n\titem_name\x18\x02 \x01(\t\x12\x12\n\nitem_price\x18\x03 \x01(\t\x12\x18\n\x10item_description\x18\x04 \x01(\t\x12\x13\n\x0bitem_weight\x18\x05 \x01(\t\x12\x17\n\x0fitem_categories\x18\x06 \x01(\t\"(\n\x15Search_ItemID_request\x12\x0f\n\x07item_id\x18\x01 \x01(\t\"6\n\x16Search_ItemID_response\x12\x1c\n\x07item_id\x18\x01 \x01(\x0b\x32\x0b.items.Item2W\n\x05Items\x12N\n\rSearch_ItemID\x12\x1c.items.Search_ItemID_request\x1a\x1d.items.Search_ItemID_response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'items_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ITEM._serialized_start=23
  _ITEM._serialized_end=157
  _SEARCH_ITEMID_REQUEST._serialized_start=159
  _SEARCH_ITEMID_REQUEST._serialized_end=199
  _SEARCH_ITEMID_RESPONSE._serialized_start=201
  _SEARCH_ITEMID_RESPONSE._serialized_end=255
  _ITEMS._serialized_start=257
  _ITEMS._serialized_end=344
# @@protoc_insertion_point(module_scope)
