# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import items_pb2 as items__pb2


class ItemsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search_ItemID = channel.unary_unary(
                '/items.Items/Search_ItemID',
                request_serializer=items__pb2.Search_ItemID_request.SerializeToString,
                response_deserializer=items__pb2.Search_ItemID_response.FromString,
                )


class ItemsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Search_ItemID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ItemsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Search_ItemID': grpc.unary_unary_rpc_method_handler(
                    servicer.Search_ItemID,
                    request_deserializer=items__pb2.Search_ItemID_request.FromString,
                    response_serializer=items__pb2.Search_ItemID_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'items.Items', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Items(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Search_ItemID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/items.Items/Search_ItemID',
            items__pb2.Search_ItemID_request.SerializeToString,
            items__pb2.Search_ItemID_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
