FROM python:3.8

# set a directory for the app
WORKDIR C:\Users\Owner\Documents\UChicago\Fall_2022\Topics_in_SWE\Project\User_Service

# copy all the files to the container
COPY . .

# install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# define the port number the container should expose
EXPOSE 5000

# run the command
ENTRYPOINT [ "python" ]

CMD ["app.py" ]
# CMD ["python", "./app.py"]